input: data/VIRAT2.mp4
output: data/VIROUTLsegcont.mp4
yolo_weights: weights/yolov8n.pt
action_model: x3d_custom
action_label_map: config/custom_action_labels.txt
enable_segmentation: true
seg_weights: weights/yolov8n-seg.pt
enable_scene_segmentation: true
visualize_scene_segmentation: true
scene_segmentation_model: nvidia/segformer-b0-finetuned-ade-512-512
tracker: config/botsort_best_quality.yaml
device: cuda:0
infer_stride: 8
scene_segmentation_frame_idx: 0
event_log_path: logs/virat_events.jsonl
event_log_frames: true
save_events_db: true
db_run_name: virat2_db_run
action_expand_scale: 1.4
scene_context_expansion: 1.5
scene_context_topk: 3